---
{% raw %}
- name: Automate building ISO image for deploying grid platforms
  hosts: localhost
  gather_facts: yes

  tasks:
  - name: Create image installer
    ansible.builtin.import_role:
      name: rprakashg.vpac.create_image_installer
  - name: Create iso with custom kickstart
    ansible.builtin.import_role:
      name: rprakashg.vpac.create_iso
{% endraw %}
...